services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    environment:
      PORT: 4000
      FRONTEND_DIR: /app/frontend
      REPLICAS: "http://replica1:5001,http://replica2:5002,http://replica3:5003"
      LEADER_POLL: "1000"
    ports:
      - "4000:4000"
    networks:
      - raft-net
    depends_on:
      replica1:
        condition: service_healthy
      replica2:
        condition: service_healthy
      replica3:
        condition: service_healthy

  replica1:
    build:
      context: ./replica
    environment:
      NODE_ID: replica1
      PORT: 5001
      PEERS: "http://replica2:5002,http://replica3:5003"
    ports:
      - "5001:5001"
    networks:
      - raft-net
    volumes:
      - ./replica:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5001/status"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s

  replica2:
    build:
      context: ./replica
    environment:
      NODE_ID: replica2
      PORT: 5002
      PEERS: "http://replica1:5001,http://replica3:5003"
    ports:
      - "5002:5002"
    networks:
      - raft-net
    volumes:
      - ./replica:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5002/status"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s

  replica3:
    build:
      context: ./replica
    environment:
      NODE_ID: replica3
      PORT: 5003
      PEERS: "http://replica1:5001,http://replica2:5002"
    ports:
      - "5003:5003"
    networks:
      - raft-net
    volumes:
      - ./replica:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5003/status"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s

networks:
  raft-net:
    driver: bridge
